### ISSUE TITLE
你好，请问有human3.6m的数据集吗，repo里的dropbox链接失效了，谢谢

### ISSUE THREAD

**Issue by BennyWnj** [daidai1230/videopose3d#7]
同上

**Comment by daidai1230** [comment]
https://drive.google.com/file/d/1GL8U2r_lADKsBQM6q-J7gODe8Gwl-Eb_/view?usp=sharing

但这个也只是关键点的数据集。没有视频数据

**Comment by daidai1230** [comment]
> 同上

https://drive.google.com/file/d/1GL8U2r_lADKsBQM6q-J7gODe8Gwl-Eb_/view?usp=sharing

但这个也只是关键点的数据集。没有视频数据

**Comment by BennyWnj** [comment]
> > 同上
> 
> https://drive.google.com/file/d/1GL8U2r_lADKsBQM6q-J7gODe8Gwl-Eb_/view?usp=sharing
> 
> 但这个也只是关键点的数据集。没有视频数据

好的谢谢
